sudo: false
language: python
cache: pip
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test tests/
deploy:
  provider: heroku
  api_key:
    secure: b0/BBvzPi+r1uU8AOH5ZHd9B7QAgjqgYNljP8OCWcX9hI6BO8iDljzEGJ915tlWO7rcBKJqbVvB2GkyzBxZ8uznVcevtSB1MKb7WAMwrdHLaTuiNQinktVG93tQBsEqloZKNN46nvutEsxJIw/ttaXUTLO0UMAMzxzoCGsX1GsALKJyiTEQBQKHwi08jkaZ/tKorNdpAT4izmmZBFSJFLeOt+v9TylC5yzefkloTCIIqv4WDVx6DNgTIm86ufQ+A3yxolJRUMzRhHtU4X1f2gnGJ9cgKh3fno3Ul2yq+vmWI+ctD9yOSpDm288sK3vKfXXUZ/47Ge7ydU56uAOhww5nLzEMdwufEXKxOICB3vtEincEsDzC+974uTnIcTTqvgqVpz6//y/DIH6lJnq+uio8S4qWVbMQpNmHsOuAdlgD3t9Uj8jOX8A6qQt6bd935NuJwncb5tfpaw/2CZli4WbY8O2PHdackoLPw0l+cIhIH4fix1Uni7UJ+3q78+NJ8bxpGPuxEbMbCWO5Vy4XI9HOytYBu+5tG9ypnB4WqeBVSVQ0RV3FTIsy3L9cZhJR7+3wluL0QLvhmnoedmN+35HQ46cwWB0uRvRwaIQ1kgep9vt1wzK7hjDrI9MRCC/M+16UxPvfW3DrgvDfGJ8hT6ds9E/MbpbSP2HIYsamNOA0=
  app: cmput404w19-project
  run:
  - python manage.py makemigrations
  - python manage.py migrate
