sudo: false
language: python
cache: pip
before_install:
  - sudo apt-get install -y libxml2-dev
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
python:
- 3.6
install:
- pip install -r requirements.txt
env:
- DB=sqlite
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test tests/ --pattern="*Test.py"
deploy:
  provider: heroku
  api_key:
    secure: RZ3eNvTkzJE/EWcpOJyTa38obQRe8HfFSHCtq1y6bCxi1nOjrKw6Kc14BeoZAbpvyPwkSzFT+fX2rf+zQCH8pGQtoeVMH636vc/lUM96MlBx7VOq+EZqDDZynbZH/UvGrA1dZWDKpMOL+uL3RE/bFqPx1Sz782x+tjjsZyr7xtPq0pF8VYXmHNJjniy0labuhrW+zjn2FWR2SOtu4/xsS4wNPhwEL9H8jJvWPGv7LTs7z32p1kCPdDf3jJ6HwSNYeCoBmsWFQ2BV2vvpPxrGmz+CMqfzpApjiVWC+U78vbER12/TZ5ipOSnUS330R1Q1WM4RLtYMLWUG3thhdLjeJ51ORzzyTxLOrus+arSVWCse3eHZEgr416ZOpifvXw3PHrDHWfYUPRepGNNKOU7ufK2jLG6xyJ9eECEXmYxYxLHFCN7L3GisE/lUbiXxlGdj0XNHfelx6eLxFdtyHD0NUhDtbFYFhtdtvJTxANS9XA2FUFjMazxw2zPtAJ1R/K/fCwTXUR2FIuiAoD5fcvHlPtmkhlXgT3efUBc6F6v+VHrWBjkLaA0IWKKyR3HO7HUkiU9ra0L8Uwuvn0hdMvcSwfscB2w/UDmsU7Rim1sSe3NvcS66SG2okUKbkamsY7tpd7bjorpYNZBf/FlzlNQ1VUvKJRxT+1tGXCjn6ulMYUg=
  app: cmput404w19-web-project
  run:
  - python manage.py makemigrations
  - python manage.py migrate
