# Generated by Django 2.1.7 on 2019-03-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_url', 'following_url')},
        ),
    ]
