# Generated by Django 2.1.7 on 2019-03-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190328_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedBy_id',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedTo_id',
            field=models.URLField(default=''),
        ),
    ]
