# Generated by Django 2.1.7 on 2019-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190329_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.URLField(default=''),
        ),
    ]
