# Generated by Django 2.1.7 on 2019-03-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190329_0101'),
        ('accounts', '0002_auto_20190328_2308'),
    ]

    operations = [
    ]
