# Generated by Django 2.1.7 on 2019-03-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20190329_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='requestedBy_id',
            new_name='requestedBy_url',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='requestedTo_id',
            new_name='requestedTo_url',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requestedBy_url', 'requestedTo_url')},
        ),
    ]
