# Generated by Django 2.1.7 on 2019-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190314_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file64',
            field=models.FileField(default='', upload_to='usr_file/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image64',
            field=models.ImageField(default='', upload_to='usr_img/'),
        ),
    ]
