# Generated by Django 2.1.7 on 2019-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190315_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='refPost',
            field=models.CharField(default='', max_length=20),
        ),
    ]
