# Generated by Django 2.1.7 on 2019-03-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20190329_0314'),
        ('accounts', '0005_post_host'),
    ]

    operations = [
    ]
