# Generated by Django 2.1.7 on 2019-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_post_refpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='refPost',
            field=models.CharField(default='', max_length=200),
        ),
    ]
