# Generated by Django 2.1.7 on 2019-03-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190315_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish_time',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_time',
            new_name='published',
        ),
    ]
