# Generated by Django 2.1.7 on 2019-03-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190329_1048'),
        ('accounts', '0005_auto_20190329_0638'),
    ]

    operations = [
    ]
