# Generated by Django 2.1.7 on 2019-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20190329_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedBy_url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
