# Generated by Django 2.1.7 on 2019-03-09 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20190309_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('requestedBy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedBY', to=settings.AUTH_USER_MODEL)),
                ('requestedTo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedTO', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='following_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_id', 'following_id')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requestedBy_id', 'requestedTo_id')},
        ),
    ]
