# Generated by Django 2.1.7 on 2019-03-09 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190309_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedBy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedBY', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedTo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedTO', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='postvisibeto',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
