# Generated by Django 2.1.7 on 2019-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190329_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='requestedBy_name',
            field=models.CharField(default='unknown user', max_length=20),
        ),
    ]
