# Generated by Django 2.1.7 on 2019-04-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190407_2356'),
        ('accounts', '0013_auto_20190408_0108'),
    ]

    operations = [
    ]
